### ISSUE TITLE
Attribute Mechanic bug[Bug]: 

### ISSUE THREAD

**Issue by redkk0523** [promcteam/proskillapi#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bug when doing attribute calculations 
for ex. doing 

![image](https://user-images.githubusercontent.com/92325343/139907489-7bbb0b98-cab2-4a54-b5a8-f3d4c071216b.png)

my goal initially was to make a skill that once learn will multiply current attr in a global level to X.XX

will not work even tring with a cast trigger instead of initialize still wont work

using all updated plugins 
![image](https://user-images.githubusercontent.com/92325343/139908145-7f1d41bb-8277-499a-b167-4d9e1bceaab6.png)

### Expected Behavior

should multiply attribute in a global level 

### Steps To Reproduce

initialize > passive > Attribute mechanic 

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

### latest.log

02.11 20:25:43 [Server] WARN Task #184100 for ProSkillAPI v1.1.7.3-ALPHA generated an exception
02.11 20:25:43 [Server] INFO java.lang.IllegalArgumentException: No enum constant com.sucy.skill.api.enums.Operation.operation
02.11 20:25:43 [Server] INFO at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
02.11 20:25:43 [Server] INFO at com.sucy.skill.api.enums.Operation.valueOf(Operation.java:6) ~[ProSkillAPI-1.1.7.3-ALPHA.jar:?]
02.11 20:25:43 [Server] INFO at com.sucy.skill.dynamic.mechanic.AttributeMechanic.execute(AttributeMechanic.java:83) ~[ProSkillAPI-1.1.7.3-ALPHA.jar:?]
02.11 20:25:43 [Server] INFO at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:242) ~[ProSkillAPI-1.1.7.3-ALPHA.jar:?]
02.11 20:25:43 [Server] INFO at com.sucy.skill.dynamic.condition.ConditionComponent.execute(ConditionComponent.java:31) ~[ProSkillAPI-1.1.7.3-ALPHA.jar:?]
02.11 20:25:43 [Server] INFO at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:242) ~[ProSkillAPI-1.1.7.3-ALPHA.jar:?]
02.11 20:25:43 [Server] INFO at com.sucy.skill.dynamic.mechanic.PassiveMechanic.access$500(PassiveMechanic.java:43) ~[ProSkillAPI-1.1.7.3-ALPHA.jar:?]
02.11 20:25:43 [Server] INFO at com.sucy.skill.dynamic.mechanic.PassiveMechanic$PassiveTask.run(PassiveMechanic.java:124) ~[ProSkillAPI-1.1.7.3-ALPHA.jar:?]
02.11 20:25:43 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-327]
02.11 20:25:43 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-327]
02.11 20:25:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-327]
02.11 20:25:43 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-327]
02.11 20:25:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-327]
02.11 20:25:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-327]
02.11 20:25:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-327]
02.11 20:25:43 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]

### Anything else?

thank for your continued support with this plugin i love you all <3

**Comment by Travja** [comment]
Can you attach the applicable skill as well?

**Comment by redkk0523** [comment]
```
TestAttrCalc:
  name: 'TestAttrCalc'
  type: 'Dynamic'
  max-level: 1
  skill-req: ''
  skill-req-lvl: 1
  needs-permission: 'False'
  msg: '&6{player} &2has cast &6{skill}'
  combo: ''
  indicator: '2D'
  icon: 'Jack o lantern'
  icon-data: 0
  icon-lore:
  - 'Multiplies Base Stat by '
  attributes:
    level-base: 1
    level-scale: 0
    cost-base: 1
    cost-scale: 0
    cooldown-base: 0
    cooldown-scale: 0
    mana-base: 0
    mana-scale: 0
    points-spent-req-base: 0
    points-spent-req-scale: 0
    incompatible:
    - ''
  components:
    Initialize-a:
      type: 'trigger'
      data:
        icon-key: ''
      children:
        Passive-b:
          type: 'mechanic'
          data:
            icon-key: ''
            counts: 'True'
            seconds-base: 1
            seconds-scale: 0
          children:
            Attribute-c:
              type: 'mechanic'
              data:
                icon-key: 'Dexchk'
                counts: 'True'
                key: 'Dexterity'
                operation: 'MULTIPLY_PERCENTAGE'
                amount-base: 50
                amount-scale: 0
                seconds-base: 99999
                seconds-scale: 0
                stackable: 'False'

```

**Comment by redkk0523** [comment]
> Can you attach the applicable skill as well?

```
TestAttrCalc:
  name: 'TestAttrCalc'
  type: 'Dynamic'
  max-level: 1
  skill-req: ''
  skill-req-lvl: 1
  needs-permission: 'False'
  msg: '&6{player} &2has cast &6{skill}'
  combo: ''
  indicator: '2D'
  icon: 'Jack o lantern'
  icon-data: 0
  icon-lore:
  - 'Multiplies Base Stat by '
  attributes:
    level-base: 1
    level-scale: 0
    cost-base: 1
    cost-scale: 0
    cooldown-base: 0
    cooldown-scale: 0
    mana-base: 0
    mana-scale: 0
    points-spent-req-base: 0
    points-spent-req-scale: 0
    incompatible:
    - ''
  components:
    Initialize-a:
      type: 'trigger'
      data:
        icon-key: ''
      children:
        Passive-b:
          type: 'mechanic'
          data:
            icon-key: ''
            counts: 'True'
            seconds-base: 1
            seconds-scale: 0
          children:
            Attribute-c:
              type: 'mechanic'
              data:
                icon-key: 'Dexchk'
                counts: 'True'
                key: 'Dexterity'
                operation: 'MULTIPLY_PERCENTAGE'
                amount-base: 50
                amount-scale: 0
                seconds-base: 99999
                seconds-scale: 0
                stackable: 'False'

```

https://www.dropbox.com/s/vybxqd1oj92fm3n/TestAttrCalc.yml?dl=1 for the file itself
