### ISSUE TITLE
[Bug]: Effects

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

square, pentagon, hexagon do not look like square, pentagon, hexagon
effect lines always use world directions for facing meaning they will never be able to rotate or face other ways
effect formula is hard to understand in terms of why it is drawn that way

### Expected Behavior

square, pentagon, hexagon to look like square, pentagon, hexagon
effect lines to behave like the formula in any math graph
possible new options:
  - facing-player: true (player-facing) -> the effect would use the horizontal or vertical looking angle as its starting angle depending on how its placed
  - angle: 45 -> rotates the shape 45 deg clockwise (can stack with the option above)

### Environment

```markdown
- Server Software: all
- ProSkillAPI Version: all
- ProMCCore Version: all
```

### Anything else?

Square:
![square before](https://user-images.githubusercontent.com/74104790/146988121-8c85dcd6-0d63-4a05-a7de-6c5fa6c7b0c4.png)

Pentagon:
![pentagon before](https://user-images.githubusercontent.com/74104790/146988144-7c9fd705-d78b-4e6a-b646-1454cd1cbe95.png)

Hexagon:
![hexagon before](https://user-images.githubusercontent.com/74104790/146988180-bed65fde-9830-4497-b90d-823eca6b3e21.png)

**Comment by Travja** [comment]
This is definitely one of those things that, when I see the particles, I just wonder why the heck the "shapes" are the way they are. In order to resolve this issue, I'll likely be adjusting those formulas and possibly re-working the particle system. I'm currently thinking something like being able to specify the number of sides that the shape has as well as initial rotation of the overall shape. Then maybe also throwing in each line segment rotation. I don't know, there's a lot that could be done with this and what's already there isn't super great at the moment. Haha

**Comment by Travja** [comment]
Through some experimentation, and using your formulas from Discord as a reference, I found some decent formulas for the shapes that'll work nicely for the shapes themselves. Though the square is corner to corner, just like your examples were. I hesitate to redo the effect system because what's there is actually somewhat decent in terms of making nice circular or spiral effects, it just struggles with geometric shapes quite a bit.

Anywho, here is the corrected formulas. I'll be adding this as the default in the effects.yml from here-on-out.
```yaml
square:
  formula: '1/(c+(t*4))'
  steps: '5'
  copies: '4'
  domain: '0.26'
  x: '0'
  y: '0'
  z: '0'
pentagon:
  formula: '1/(c+(t*3.4))'
  steps: '5'
  copies: '5'
  domain: '0.2'
  x: '0'
  y: '0'
  z: '0'
hexagon:
  formula: '1/(c+(t*2.8))'
  steps: '5'
  copies: '6'
  domain: '0.17'
  x: '0'
  y: '0'
  z: '0'
```
