### ISSUE TITLE
"Focus" skill will replace other attributes in /class attr GUI

### ISSUE THREAD

**Issue by trojohnwick** [promcteam/proskillapi#463]
1. When I use /class attr gui it takes my '1' slot attribute, focus, and turns all of slots 11 on through the second row in to focus. Even using multiple pages it does the same thing.  Tried inserting 2 and 3 and slots, and just about every combo of everything. It won't even open (internal error) now, unless I remove the slots entirely.
`ATTRIBUTES: 
  rows: 3
  pages: 1
  slots:
    1:
      vitality: 0
      focus: 1
      dexterity: 2
      intellect: 3
      luck: 4
      mastery: 5
      agility: 6
      leanness: 7
      focus: 8
      spirit: 9
      storm-mastery: 10
      abjuration-mastery: 11
      diablerie-mastery: 12
      restoration-mastery: 13
      primordial-mastery: 14
      strength: 18
      endurance: 19
      grounded: 20
`
![image](https://user-images.githubusercontent.com/129621247/232275162-2e9b4798-26b3-4bfe-8ad1-81cab1c54af7.png)
```
focus: 
  display: 'Focus'
  max: '75'
  icon: 'paper'
  icon-data: '0'
  icon-lore: 
  - '&6Focus &7(&2{amount}&7)'
  - ''
  - '&7Grants 2.5% increased'
  - '&7skill damage per point'
  - '&7invested.'
  global: 
    condition:  {}
    mechanic: 
      Damage-value: 'a0.025+1v'
    target:  {}
```

2. Minor notes, but GUI needs to be locked to read or it regens. Tried to cold fresh the plugin by updating and removing configs, but it amazingly remembered the broken gui config
