### ISSUE TITLE
[Enhancement] Global skills

### ISSUE THREAD

**Issue by fructozer** [promcteam/proskillapi#527]
When creating an rpg server, sometimes you will need to create mechanisms that apply to all players. 
For example, `when a person takes damage with the classifier is pyo, they will burn for 2 seconds`

To do this at present, there are 2 ways, attach a default skill that can perform the above mechanism on each class or attach the fire mechanism every time using the damage mechanism. Both ways are very time consuming.

So, I propose a function that allows registering global skills.
Registry file: pluginsProSkillAPIglobal-skill.yml
```yaml
general-skills:
    - skill_1
    - skill_2
hiden-skills:
    - skill_a
    - skill_b
```
Both general skills and hiden skills will be added to all classes, however Hiden Skill will not be displayed in the skill tree.
